### ISSUE TITLE
Initial download of code generated a cannot GET /

### ISSUE THREAD

**Issue by lyonta** [cornflourblue/angular-10-signup-verification-boilerplate#2]
Build at: 2021-02-07T18:57:28.503Z - Hash: f76d22e9591dab0eada9 - Time: 9149ms

Error: ./src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: angularCompiler.getResourceDependencies is not a function or its return value is not iterable
    at getDependencies (C:\Software\angular-10-signup-verification-boilerplate-master\angular-10-signup-verification-boilerplate-master\node_modules\@ngtools\webpack\src\ivy\plugin.js:262:56)
    at C:\Software\angular-10-signup-verification-boilerplate-master\angular-10-signup-verification-boilerplate-master\node_modules\@ngtools\webpack\src\ivy\plugin.js:375:20
    at analyzingFileEmitter (C:\Software\angular-10-signup-verification-boilerplate-master\angular-10-signup-verification-boilerplate-master\node_modules\@ngtools\webpack\src\ivy\plugin.js:308:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: ./src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: angularCompiler.getResourceDependencies is not a function or its return value is not iterable
    at getDependencies (C:\Software\angular-10-signup-verification-boilerplate-master\angular-10-signup-verification-boilerplate-master\node_modules\@ngtools\webpack\src\ivy\plugin.js:262:56)
    at C:\Software\angular-10-signup-verification-boilerplate-master\angular-10-signup-verification-boilerplate-master\node_modules\@ngtools\webpack\src\ivy\plugin.js:375:20
    at analyzingFileEmitter (C:\Software\angular-10-signup-verification-boilerplate-master\angular-10-signup-verification-boilerplate-master\node_modules\@ngtools\webpack\src\ivy\plugin.js:308:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

[39m

**Comment by lyonta** [comment]
First time ran a npm audit fix for issues found.  Second time did not and then the login page appeared
